### ISSUE TITLE
Error in running videofy since the new patch.

### ISSUE THREAD

**Issue by indianquant** [mohtamohit/Videofy#8]
Traceback (most recent call last):
  File "videofy.py", line 225, in <module>
    clp = ImageClip("images/"+str(i)+".jpg").resize(width = w, height = h).set_pos(('center','center')).fl_image(lambda pic: (0.6*pic).astype('int16'))
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/VideoClip.py", line 965, in __init__
    img = imread(img)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 185, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 99, in get_reader
    request = Request(uri, 'r' + mode, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 118, in __init__
    self._parse_uri(uri)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 250, in _parse_uri
    raise IOError("No such file: '%s'" % fn)
OSError: No such file: '/opt/lampp/ht

**NOTE** I have tried to create a separate anaconda environment and install the libraries accordingly. Stil the problem persists.

**Comment by surya-veer** [comment]
This is because of permissions.The script is unable to download images.
Check permissions of HTDOCS folder. It should be 776.
